language: python
python:
  - "3.8"
services:
  - postgresql
env:
  -DJANGO=1.8
install:
  - pip install -r backend/src/requirements.txt
before_script:
  - psql -c 'create database gis;' -U postgres
script:
  - cd backend/src
  - python manage.py tests