runtime: python37
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.app

libraries:
- name: Click
  version: "7.0"

- name: Flask
  version: "1.1.1"

- name: gunicorn
  version: "20.0.4"

- name: itsdangerous
  version: "1.1.0"

- name: Jinja2
  version: "2.11.1"

- name: MarkupSafe
  version: "1.1.1"

- name: pymongo
  version: "3.10.1"

- name: Werkzeug
  version: "1.0.0"

# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10