# Generated by Django 3.1.4 on 2020-12-28 23:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, default=0.0, max_digits=12)),
                ('lng', models.DecimalField(decimal_places=10, default=0.0, max_digits=13)),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Not Working'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('feature', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Bottle Refiller'), (1, 'Kid Friendly'), (2, 'Accesible'), (3, 'Pet Fiendly')], max_length=7, null=True)),
                ('access', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10)),
                ('location', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Outdoor', max_length=10)),
            ],
        ),
    ]
