# Generated by Django 3.1.4 on 2020-12-28 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fountain',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last Update'),
            preserve_default=False,
        ),
    ]
