# Generated by Django 3.1.4 on 2020-12-28 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fountain', '0003_fountainupdatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fountain_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fountian_updates', to='fountain.fountain', verbose_name='Originial Fountain')),
                ('fountain_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fountian_updates', to='fountain.fountainupdatemodel', verbose_name='Modified Fountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_fountians', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
