# Generated by Django 3.1.4 on 2020-12-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0004_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fountain',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='fountain',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='fountainupdatemodel',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='fountainupdatemodel',
            name='lng',
        ),
    ]
