# Generated by Django 3.1.4 on 2020-12-31 17:13

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0005_auto_20201231_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='fountain',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
        migrations.AddField(
            model_name='fountainupdatemodel',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
