# Generated by Django 3.1.4 on 2020-12-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0006_auto_20201231_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fountain',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Update'),
        ),
    ]
