# Generated by Django 3.1.4 on 2021-01-04 00:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0008_auto_20210103_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fountain',
            name='feature',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Bottle Refiller'), (1, 'Kid Friendly'), (2, 'Accesible'), (3, 'Pet Fiendly')], max_length=7, null=True, verbose_name='Fountian Features'),
        ),
        migrations.AlterField(
            model_name='fountainupdatemodel',
            name='feature',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Bottle Refiller'), (1, 'Kid Friendly'), (2, 'Accesible'), (3, 'Pet Fiendly')], max_length=7, null=True, verbose_name='Fountian Features'),
        ),
    ]
