# Generated by Django 3.1.4 on 2021-01-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0009_auto_20210104_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
