# Generated by Django 3.1.4 on 2020-12-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar of user', upload_to='Avatar', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_fountains',
            field=models.ManyToManyField(related_name='users_liked', to='fountain.Fountain', verbose_name='Liked Fountains'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_fountains',
            field=models.ManyToManyField(related_name='users_saved', to='fountain.Fountain', verbose_name='Saved Fountians'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
