# Generated by Django 3.1.4 on 2020-12-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0007_auto_20201231_2247'),
        ('users', '0002_auto_20201228_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_fountains',
            field=models.ManyToManyField(related_name='user_created', to='fountain.Fountain', verbose_name='Created Fountains'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_fountains',
            field=models.ManyToManyField(related_name='users_updated', to='fountain.Fountain', verbose_name='Updated Fountains'),
        ),
    ]
