# Generated by Django 3.1.4 on 2021-01-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_auto_20210104_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users_in_group', to='auth.Group', verbose_name='Groups'),
        ),
    ]
