language: python # => 1
    python: # => 2
      - "3.8"
    services: # => 3
      - postgresql
    env: # => 4
      -DJANGO=1.8
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - psql -c 'create database gis;' -U testUser
    script: # => 7
      - python manage.py tests