# Generated by Django 3.1.4 on 2020-12-29 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_fountain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
