# Generated by Django 3.1.4 on 2020-12-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fountain_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='fountain',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10),
        ),
    ]
