# Generated by Django 3.1.4 on 2020-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201227_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fountain',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
