# Generated by Django 3.1.4 on 2020-12-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fountain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fountain',
            name='feature',
            field=models.IntegerField(blank=True, choices=[(0, 'Bottle Refiller'), (1, 'Kid Friendly'), (2, 'Accesible'), (3, 'Pet Fiendly')], null=True),
        ),
    ]
