# Generated by Django 3.1.4 on 2020-12-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fountain_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='fountain',
            name='location',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Outdoor', max_length=10),
        ),
    ]
