# Generated by Django 3.1.4 on 2020-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fountain_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fountain',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fountain',
            name='lng',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
    ]
